# Generated by Django 5.2.5 on 2025-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_flutterwavetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutterwavetransaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flutterwavetransaction',
            name='object_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flutterwavetransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='flutterwavetransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
