# Generated by Django 5.2.5 on 2025-08-16 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p1', to=settings.AUTH_USER_MODEL)),
                ('participant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p2', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The content of the message.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates if the message has been read by the recipient.')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the message was sent.')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Success', 'Success'), ('Error', 'Error')], default='Info', max_length=20)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('page_type', models.CharField(blank=True, choices=[('default', 'Default/Fallback'), ('home', 'Homepage'), ('contact', 'Contact Page'), ('about', 'About Page')], max_length=50, null=True, unique=True)),
                ('meta_title', models.CharField(max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG Title (Facebook/LinkedIn)')),
                ('og_description', models.TextField(blank=True, verbose_name='OG Description (Facebook/LinkedIn)')),
                ('og_image_url', models.URLField(blank=True, verbose_name='OG Image URL')),
                ('og_image_alt', models.CharField(blank=True, max_length=255, verbose_name='OG Image Alt Text')),
                ('og_type', models.CharField(blank=True, default='website', max_length=50, verbose_name='OG Type (e.g., website, article)')),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', max_length=50, verbose_name='Twitter Card Type')),
                ('twitter_site', models.CharField(blank=True, max_length=100, verbose_name='Twitter Site (@handle)')),
                ('twitter_title', models.CharField(blank=True, max_length=255, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, verbose_name='Twitter Description')),
                ('twitter_image_url', models.URLField(blank=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Meta Tag',
                'verbose_name_plural': 'SEO Meta Tags',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_timestamp'], name='core_conver_last_me_268443_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant1', 'participant2')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sent_at'], name='core_messag_sent_at_7d3b57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seo',
            unique_together={('content_type', 'object_id')},
        ),
    ]
