# Generated by Django 5.2.5 on 2025-12-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_contactmessage_replied_contactmessage_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'SEO Settings', 'verbose_name_plural': 'SEO Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='seo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seo',
            name='address_city',
            field=models.CharField(blank=True, default='Dar es Salaam', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='address_country',
            field=models.CharField(blank=True, default='TZ', max_length=2),
        ),
        migrations.AddField(
            model_name='seo',
            name='address_postal',
            field=models.CharField(blank=True, default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='seo',
            name='address_region',
            field=models.CharField(blank=True, default='DSM', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='address_street',
            field=models.CharField(blank=True, default='123 Language Street', max_length=200),
        ),
        migrations.AddField(
            model_name='seo',
            name='area_served',
            field=models.CharField(blank=True, default='TZ', max_length=50),
        ),
        migrations.AddField(
            model_name='seo',
            name='area_served_name',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='bing_site_verification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/langtouch'),
        ),
        migrations.AddField(
            model_name='seo',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500000, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/langtouch'),
        ),
        migrations.AddField(
            model_name='seo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/langtouch'),
        ),
        migrations.AddField(
            model_name='seo',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=50000, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='og_image_height',
            field=models.IntegerField(default=630),
        ),
        migrations.AddField(
            model_name='seo',
            name='og_image_width',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='seo',
            name='organization_logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='organization_name',
            field=models.CharField(default='Langtouch', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='organization_phone',
            field=models.CharField(blank=True, default='+255-123-456-789', max_length=20),
        ),
        migrations.AddField(
            model_name='seo',
            name='price_range',
            field=models.CharField(blank=True, default='TZS 50,000 - 500,000', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='rating_value',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='seo',
            name='review_count',
            field=models.IntegerField(default=127),
        ),
        migrations.AddField(
            model_name='seo',
            name='robots_meta',
            field=models.CharField(default='index, follow', max_length=200),
        ),
        migrations.AddField(
            model_name='seo',
            name='twitter_creator',
            field=models.CharField(blank=True, default='@langtouch', max_length=100),
        ),
        migrations.AddField(
            model_name='seo',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://twitter.com/langtouch'),
        ),
        migrations.AddField(
            model_name='seo',
            name='yandex_site_verification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seo',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='seo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seo',
            name='meta_title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_image_alt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_type',
            field=models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('service', 'Service'), ('course', 'Course')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('service', 'Service'), ('course', 'Course'), ('blog', 'Blog Post'), ('about', 'About Page'), ('contact', 'Contact Page'), ('quote', 'Quote Request'), ('booking', 'Booking'), ('faq', 'FAQ'), ('other', 'Other')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', max_length=50),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_site',
            field=models.CharField(blank=True, default='@langtouch', max_length=100),
        ),
        migrations.AlterField(
            model_name='seo',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddIndex(
            model_name='seo',
            index=models.Index(fields=['content_type', 'object_id'], name='core_seo_content_1a231f_idx'),
        ),
        migrations.AddIndex(
            model_name='seo',
            index=models.Index(fields=['page_type'], name='core_seo_page_ty_4159f6_idx'),
        ),
        migrations.AddIndex(
            model_name='seo',
            index=models.Index(fields=['is_active'], name='core_seo_is_acti_3cab44_idx'),
        ),
    ]
